bot:
  build: .
  command: python main.py
  restart: always
  volumes:
    - ./local_config_main.py:/usr/src/app/local_config.py
  links:
    - mysql

useraddbot:
  build: .
  command: python useraddbot.py
  restart: always
  volumes:
    - ./local_config_useradd.py:/usr/src/app/local_config.py
  links:
    - mysql

mysql:
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
